package is.interpreter;

public enum Symbol {
    INVALID_CHAR, NEW, DEL, MV, MVOFF, SCALE, LS, ALL, GROUPS, GRP, UNGRP, AREA, POINT, PERIMETER, CIRCLE, RECTANGLE, IMG, LEFT_PARENTHESIS, RIGHT_PARENTHESIS, COMA, EOF,WORD, QUOTED_STRING, SLASH, COLON, MINUS,GRAMMAR

}
